// <auto-generated />
using System;
using GoogleSniffer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleSniffer.Migrations
{
    [DbContext(typeof(EdugeoModel))]
    [Migration("20210107133054_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GoogleSniffer.Escuela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EdArtistica")
                        .HasColumnType("bit");

                    b.Property<bool>("EdComun")
                        .HasColumnType("bit");

                    b.Property<bool>("EdEspecial")
                        .HasColumnType("bit");

                    b.Property<bool>("EdJovenesAdultos")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsPublico")
                        .HasColumnType("bit");

                    b.Property<bool>("EsUrbano")
                        .HasColumnType("bit");

                    b.Property<int?>("GeoMarkerId")
                        .HasColumnType("int");

                    b.Property<bool>("Inicial")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primaria")
                        .HasColumnType("bit");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Secundaria")
                        .HasColumnType("bit");

                    b.Property<bool>("Tecnica")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GeoMarkerId");

                    b.ToTable("Escuelas");
                });

            modelBuilder.Entity("GoogleSniffer.GeoMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DireccionFormateada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeoMarkers");
                });

            modelBuilder.Entity("GoogleSniffer.Escuela", b =>
                {
                    b.HasOne("GoogleSniffer.GeoMarker", "GeoMarker")
                        .WithMany()
                        .HasForeignKey("GeoMarkerId");

                    b.Navigation("GeoMarker");
                });
#pragma warning restore 612, 618
        }
    }
}
